# mkdocs.yml
site_name: Xians.ai Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    primary: custom    # Using custom color
    accent: purple    # Using predefined color
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant

extra_css:
  - stylesheets/extra.css

nav:
  - Home: 
    - Introduction: index.md
    - Setting Up: 1-getting-started/1-setting-up.md
    - Your First Agent: 1-getting-started/2-first-agent.md
    - Agent with Activities: 1-getting-started/3-activity-flow.md
  - Agent Knowledge:
    - Manage Knowledge: 2-knowledge/1-manage-knowledge.md
    - Agent Without Knowledge: 2-knowledge/2-without-knowledge.md
    - Using Knowledge: 2-knowledge/3-using-knowledge.md
  - Agent Tools:
    - What are Agent Tools: 3-tools/1-agent-tool-types.md
    - Using Agent Tools:
      - Package Agent Tools: 3-tools/2-using-tools/1-package-tools.md
      - Docker Agent Tools: 3-tools/2-using-tools/2-docker-tools.md
      - Custom Agent Tools: 3-tools/2-using-tools/3-custom-tools.md
  - Messaging:
    - Conversation with Agent: 4-messaging/1-agent-conversations.md
    - Semantic Conversations: 4-messaging/2-semantic-conversations.md
    - Handing Over Conversations: 4-messaging/3-handing-over-conversations.md
  - Encyclopedia:
    - Multi-flow Agents: n-encyclopedia/multi-flow-agents.md
    - Signaling Agent Workflows: n-encyclopedia/signaling-agent-workflows.md
    - Unit Testing Activities: n-encyclopedia/unit-testing-activities.md
    - Priority Queues: n-encyclopedia/priority-queues.md
    - Workflow Best Practices: n-encyclopedia/wf-best-practices.md


markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true


# Directory structure:
# .
# ├── docs/
# │   ├── index.md
# │   ├── getting-started/
# │   │   ├── quickstart.md
# │   │   └── installation.md
# │   ├── api/
# │   │   ├── authentication.md
# │   │   └── endpoints.md
# │   └── guides/
# │       └── best-practices.md
# ├── mkdocs.yml
# └── .github/workflows/deploy.yml

# Update the homepage setting
use_directory_urls: true

extra:
  generator: false

# Force creation of .nojekyll file
use_directory_urls: true
strict: true