# mkdocs.yml
site_name: Xians.ai Documentation
site_description: Enterprise-grade Agent Development Kit for building, deploying, and orchestrating AI agents
site_author: Xians.ai Team
site_url: https://docs.xians.ai

# Repository information
repo_name: XiansAiPlatform/XiansAi.PublicDocs
repo_url: https://github.com/XiansAiPlatform/XiansAi.PublicDocs
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    # Navigation features
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    
    # Search features
    - search.suggest
    - search.highlight
    - search.share
    
    # Content features
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    
    # Header features
    - header.autohide
    - announce.dismiss
    
    # Table of contents
    - toc.follow
    
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  font:
    text: Inter
    code: JetBrains Mono
    
  favicon: assets/logo.png
  icon:
    logo: material/robot
    edit: material/pencil
    view: material/eye
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/external-links.js
  - javascripts/code-expand.js

nav:
  - Home: index.md
  - Architecture:
    - Why Agentic Platforms: 0-architecture/1-why-xians-platform.md
    - Xians Platform Components: 0-architecture/2-platform-components.md
    - Xians Features: 0-architecture/3-xians-core-features.md
  - Quick Start: 
    - Platform Setup: 1-getting-started/0-platform-setup.md
    - Agent Project Setup: 1-getting-started/1-agent-project-setting-up.md
    - Non-Deterministic:
      - Conversational Flow: 1-getting-started/2-first-agent.md
      - Adding Capabilities: 1-getting-started/3-adding-capabilities.md
    - Deterministic:
      - Business Process Flows: 1-getting-started/4-new-business-process.md
  - Agent Communication:
    - Introduction: 2-agent-communication/0-index.md
    - Message Basics:
      - Chat & Data Types: https://github.com/XiansAiPlatform/sdk-web-typescript/blob/main/docs/message-types.md
      - Threads & Scopes: 2-agent-communication/11-thread-and-scope.md
    - User 2 Agent:
      - TypeScript SDK: https://github.com/XiansAiPlatform/sdk-web-typescript
      - HTTP APIs: https://github.com/XiansAiPlatform/XiansAi.Server/blob/main/XiansAi.Server.Src/docs/user-api/index.md
    - Data Passing:
      - Overview: 2-agent-communication/9-data-exchange.md
      - As Messages: 2-agent-communication/8-handling-data-messages.md
      - AS RPC: 2-agent-communication/10-handling-data-rpc.md
    - Agent 2 User:
      - Send Message: 2-agent-communication/2-messaging.md
      - Manual Responding: 2-agent-communication/4-responding.md
      - Skip LLM Response: 2-agent-communication/5-skip-llm-response.md
      - Welcome Message: 2-agent-communication/12-welcome-msg.md
    - Interceptors:
      - Intercept Chat: 2-agent-communication/7-chat-interceptors.md
    - Agent 2 Agent:
      - Event Passing: 2-agent-communication/1-events.md
      - Handoffs: 2-agent-communication/3-handoffs.md
      - Forwarding: 2-agent-communication/6-forward-message.md
  - Process Automation:
    - Introduction: 4-automation/0-introduction.md
    - External Triggers: 4-automation/1-external-triggers.md
    - Scheduled Execution: 4-automation/2-scheduled-execution.md
    - Fault Tolerance: 4-automation/3-fault-tolerance.md
    - Long-Running Processes: 4-automation/4-long-running-processes.md
    - Creating Sub-Flows: 4-automation/5-creating-sub-flows.md
  - Agent Memory:
    - Knowledge:
      - Managing Knowledge: 3-knowledge/1-using-portal.md
      - Accessing Knowledge: 3-knowledge/2-accessing-knowledge.md
      - Capabilities as Knowledge: 3-knowledge/3-capabilities.md
      - Local Development: 3-knowledge/4-local-dev.md
    - Structured Objects:
      - Document Store: 3-knowledge/5-document-store.md
  - Encyclopedia:
    - Multi-flow Agents: n-encyclopedia/multi-flow-agents.md
    - Retry Policy: n-encyclopedia/retry-policy.md
    - Logging: n-encyclopedia/logging.md
    - Workflow Best Practices: n-encyclopedia/wf-best-practices.md
    - LLM Completion: n-encyclopedia/llm-completion.md
    - AgentContext: n-encyclopedia/agent-context.md
    - User Auth Configuration: n-encyclopedia/user-auth-config.md
    - Scaling Agent Flows: n-encyclopedia/scaling-agents.md
    - Chat Message Encryption: n-encyclopedia/chat-message-encryption.md
  - Platform Development:
    - Start: platform-development/setup.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Permalink to this section
  - tables
  - meta
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: XiansAiPlatform
      repo: XiansAi.PublicDocs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Configuration
use_directory_urls: true
strict: true
dev_addr: '127.0.0.1:8000'

# Customization
extra:
  generator: false
  
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XiansAiPlatform
      name: GitHub Organization
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xians
      name: Discord Community
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/xiansai
      name: Twitter
    - icon: fontawesome/solid/globe
      link: https://xians.ai
      name: Official Website
  
  # Version information
  version:
    provider: mike
    default: latest
  
  # Announcement banner
  announcement: 
    text: "🚀 Xians.ai v2.0 is now available! Check out the new features in our changelog."
    
  # Analytics (uncomment when ready)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           <a href="..." target="_blank" rel="noopener">telling us what you need</a>.

# Hooks (uncomment when needed)
# hooks:
#   - scripts/external_link_checker.py

copyright: |
  &copy; 2024 <a href="https://xians.ai" target="_blank" rel="noopener">Xians.ai</a> &nbsp;&nbsp;&nbsp;&nbsp;
  <a href="#__consent">Manage Cookies</a> &nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://xians.ai/privacy" target="_blank" rel="noopener">Privacy Policy</a> &nbsp;&nbsp;&nbsp;&nbsp;
  <a href="https://xians.ai/terms" target="_blank" rel="noopener">Terms of Service</a>