# mkdocs.yml
site_name: Xians.ai Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    primary: custom    # Using custom color
    accent: purple    # Using predefined color
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant

extra_css:
  - stylesheets/extra.css

nav:
  - Architecture:
    - Why Agentic Platforms: 0-architecture/1-why-xians-platform.md
    - Xians Platform Components: 0-architecture/2-platform-components.md
    - Xians Features: 0-architecture/3-xians-core-features.md
  - Quick Start: 
    - Platform Setup: 1-getting-started/0-platform-setup.md
    - Agent Project Setup: 1-getting-started/1-agent-project-setting-up.md
    - Non-Deterministic:
      - Conversational Flow: 1-getting-started/2-first-agent.md
      - Adding Capabilities: 1-getting-started/3-adding-capabilities.md
    - Deterministic:
      - Business Process Flow: 1-getting-started/4-new-business-process.md
      - Adding Activities: 1-getting-started/5-adding-activities.md
  - Agent Communication:
    - Introduction: 2-agent-communication/0-index.md
    - MessageTypes:
      - Chat & Data Types: https://github.com/XiansAiPlatform/sdk-web-typescript/blob/main/docs/message-types.md
    - User 2 Agent:
      - TypeScript SDK: https://github.com/XiansAiPlatform/sdk-web-typescript
      - HTTP APIs: https://github.com/XiansAiPlatform/XiansAi.Server/blob/main/XiansAi.Server.Src/docs/user-api/index.md
    - Data Passing:
      - Overview: 2-agent-communication/9-data-exchange.md
      - As Messages: 2-agent-communication/8-handling-data-messages.md
      - AS RPC: 2-agent-communication/10-handling-data-rpc.md
    - Agent 2 User:
      - Send Message: 2-agent-communication/2-messaging.md
      - Manual Responding: 2-agent-communication/4-responding.md
      - Skip LLM Response: 2-agent-communication/5-skip-llm-response.md
    - Interceptors:
      - Intercept Chat: 2-agent-communication/7-chat-interceptors.md
    - Agent 2 Agent:
      - Event Passing: 2-agent-communication/1-events.md
      - Handoffs: 2-agent-communication/3-handoffs.md
      - Forwarding: 2-agent-communication/6-forward-message.md
  - Agent Knowledge:
    - Managing Knowledge: 3-knowledge/1-using-portal.md
    - Accessing Knowledge: 3-knowledge/2-accessing-knowledge.md
    - Capabilities as Knowledge: 3-knowledge/3-capabilities.md
    - Local Development: 3-knowledge/3-local-dev.md
  - Encyclopedia:
    - Multi-flow Agents: n-encyclopedia/multi-flow-agents.md
    - Retry Policy: n-encyclopedia/retry-policy.md
    - Logging: n-encyclopedia/logging.md
    - Workflow Best Practices: n-encyclopedia/wf-best-practices.md
  - Platform Development:
    - Start: platform-development/setup.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true


# Directory structure:
# .
# ├── docs/
# │   ├── index.md
# │   ├── getting-started/
# │   │   ├── quickstart.md
# │   │   └── installation.md
# │   ├── api/
# │   │   ├── authentication.md
# │   │   └── endpoints.md
# │   └── guides/
# │       └── best-practices.md
# ├── mkdocs.yml
# └── .github/workflows/deploy.yml

# Update the homepage setting
use_directory_urls: true

extra:
  generator: false

# Force creation of .nojekyll file
use_directory_urls: true
strict: true