# mkdocs.yml
site_name: Xians.ai Docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    primary: custom    # Using custom color
    accent: purple    # Using predefined color
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: material/book-open-page-variant

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started:
    - Setting Up: 1-getting-started/1-setting-up.md
    - Your First Flow: 1-getting-started/2-first-flow.md
    - Flow with Activities: 1-getting-started/3-activity-flow.md
  - Instructions:
    - Manage Instructions: 2-instructions/1-manage-instructions.md
    - Flow Without Instructions: 2-instructions/2-without-instructions.md
    - Using Instructions: 2-instructions/3-using-instructions.md
  - Agents:
    - What are Agents: 3-agents/1-what-are-agents.md
    - Using Agents: 3-agents/2-using-agents.md
    - Creating Agents: 3-agents/3-creating-agents.md

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - minify:
      minify_html: true


# Directory structure:
# .
# ├── docs/
# │   ├── index.md
# │   ├── getting-started/
# │   │   ├── quickstart.md
# │   │   └── installation.md
# │   ├── api/
# │   │   ├── authentication.md
# │   │   └── endpoints.md
# │   └── guides/
# │       └── best-practices.md
# ├── mkdocs.yml
# └── .github/workflows/deploy.yml

# Update the homepage setting
use_directory_urls: true

extra:
  generator: false

# Force creation of .nojekyll file
use_directory_urls: true
strict: true